### ISSUE TITLE
Unable to remove items correctly

### ISSUE THREAD

**Issue by DyroS3** [zRxnx/zrx_repairkit#1]
With the latest version of zrx_utility, I found that the removal of the item is not fought for, and the server side reports the following error:
![image](https://github.com/zRxnx/zrx_repairkit/assets/64310374/4a2ac41b-f650-4b5c-ab50-008c4cc77793)
After I tested it with the following code.
```lua
  print(CORE.Shared.DumpTable(CORE.Bridge.getPlayerObject(source).removeInventoryItem(source, Config.RepairKits[index].item, 1)))
  -- CORE.Bridge.removeInventoryItem(source, Config.RepairKits[index].item, 1)
  CORE.Bridge.getPlayerObject(source).removeInventoryItem(Config.RepairKits[index].item, 1)
```
I found that using ` CORE.Bridge.getPlayerObject(source).removeInventoryItem(Config.RepairKits[index].item, 1) `, is what removes the item correctly

**Comment by zRxnx** [comment]
Looks like i forgot something to change after porting to v2

**Comment by zRxnx** [comment]
If you can do a pr would be good, curr not at home

**Comment by DyroS3** [comment]
![image](https://github.com/zRxnx/zrx_repairkit/assets/64310374/9836064e-854d-4387-a483-774940cfcf53)
I'll make additional changes, code at lines 44 and 61, and if you think it'll work I'll PR it.

**Comment by zRxnx** [comment]
👍 but please without chinese
